### ISSUE TITLE
Request to add the location of the Tesseract data directory for Ubuntu

### ISSUE THREAD

**Issue by bmivzkrp** [chrys87/ocrpdf#1]
Please add to the OCRPDF the location of the Tesseract data directory for Ubuntu:

/usr/share/tesseract-ocr/4.00/tessdata/

Many thanks for your attention to this issue.

**Comment by chrys87** [comment]
OCRPDF functionality is merged into OCRdesktop

set the path is not needed anymore thanks to using pytesseract instead of python-tesserwrap as tesseract bindings.

see here for details:
https://www.patreon.com/posts/ocrdesktop-fun-61131455
https://www.patreon.com/posts/ocrdesktop-ocr-61228691

https://github.com/chrys87/ocrdesktop
